# Generated by Django 5.0.3 on 2026-02-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xhc_blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-pub_time"],
                "verbose_name": "博客",
                "verbose_name_plural": "博客",
            },
        ),
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"verbose_name": "分类", "verbose_name_plural": "分类"},
        ),
        migrations.AlterModelOptions(
            name="blogcomment",
            options={
                "ordering": ["-pub_time"],
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="xhc_blog.blogcategory",
                verbose_name="分类",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="pub_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200, verbose_name="标题"),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="name",
            field=models.CharField(max_length=200, verbose_name="分类名称"),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="xhc_blog.blog",
                verbose_name="所属博客",
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="content",
            field=models.TextField(verbose_name="评论内容"),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="pub_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
        ),
    ]
